name: Prepare Metal Run
description: "Installs Python Dependencies from cache or from PyPI if cache is not available."

inputs:
  arch:
    description: "The architecture to use"
    required: true
  is_profiler:
    description: "Whether to load with profiler"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      if: ${{ inputs.is_profiler == 'false' }}
      with:
        name: TTMetal_build_${{ inputs.arch }}
    - uses: actions/download-artifact@v4
      if: ${{ inputs.is_profiler == 'true' }}
      with:
        name: TTMetal_build_${{ inputs.arch }}_profiler
    - name: Extract files
      shell: bash
      run: tar -xvf ttm_${{ inputs.arch }}.tar
    - uses: ./.github/actions/install-python-deps
    - name: Collect Workflow Telemetry
      if: ${{ !cancelled() }}
      uses: catchpoint/workflow-telemetry-action@v2
