name: "Run set of commands in Docker"
description: "Run commands in docker"

inputs:
  run_args:
    description: 'Commands to run in docker'
    required: true
  image:
    description: 'Docker image to run commands in - follows os-arch format'
    required: false
    default: ubuntu-20.04-amd64

runs:
  using: "composite"
  steps:
    - name: Determine Docker Tag
      shell: bash
      run: |
        if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=dev-${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
        fi
    - name: Determine Full Docker Image Tag
      shell: bash
      run: |
        echo "TT_METAL_DOCKER_IMAGE_TAG=ghcr.io/${{ github.repository }}/tt-metalium/${{ inputs.image }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
        echo "TT_METAL_REF_IMAGE_TAG=ghcr.io/${{ github.repository }}/tt-metalium/${{ inputs.image }}:latest" >> $GITHUB_ENV
    - name: Output Docker Image Tag
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"
        echo "TT_METAL_DOCKER_IMAGE_TAG=${{ env.TT_METAL_DOCKER_IMAGE_TAG}}"
