name: "[post-commit] Build C++ binaries with all configs"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-docker-image-2004:
    uses:  ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ubuntu-20.04-amd64
  build-docker-image-2204:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ubuntu-22.04-amd64
  build:
    needs: [build-docker-image-2004, build-docker-image-2204]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
