name: "(Single-card) Model perf tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,7,10,14,17,20,23 * * *"
  workflow_call:

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  models-perf:
    needs: build-artifact
    uses: ./.github/workflows/perf-models-impl.yaml
    secrets: inherit
